app = "tierschutz-wahlstimmen"
primary_region = "ams"

[env]
  PORT = "3000"

[mounts]
  source = "wahlstimmen_volume"
  destination = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
